title: <p align="center"> Kunru Lu </p>

logo: "/images/pic.png?raw=true"

description:
  <p align="center">
  <a href="https://github.com/carajumpshigh/kunrulu.github.io/blob/master/Kunru%20Lu-Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/lukunru">LinkedIn</a> |
  <a href="https://github.com/carajumpshigh">GitHub</a> |
  <a href="https://medium.com/@kl3743">Medium</a>
  </p>
  
  
  <p align="justify">
  Engineers build the engine behind a product and business leaders give it a soul. I want to bridge the gap between engineers and business leaders and guide their decisions through data science. <br> 
  Currently pursuing an MS in Urban Informatics at NYU CUSP, my goal is to attain mastery over data science to translate consumer insights into data-intensive product solutions. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
